---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfcli/cli-base

inputs:
- name: cli
  path: go/src/code.cloudfoundry.org/cli
- name: cf-cli-binaries
- name: cli-bosh-lite

params:
  CF_CLI_EXPERIMENTAL: false
  CF_INT_CLIENT_ID:
  CF_INT_CLIENT_SECRET:
  CF_INT_DOCKER_IMAGE:
  CF_INT_DOCKER_USERNAME:
  CF_INT_DOCKER_PASSWORD:
  CF_INT_IGNORE_API_VERSION_CHECK:
  NODES: 8

run:
  path: bash
  args:
  - -c
  - |
    set -e

    source cli-bosh-lite/env

    credhub login --skip-tls-validation
    export CF_INT_PASSWORD=$(credhub get --name '/bosh-lite/cf/cf_admin_password' | bosh interpolate --path /value -)
    export CF_INT_OIDC_USERNAME="admin-oidc"
    export CF_INT_OIDC_PASSWORD=$(credhub get --name '/bosh-lite/cf/uaa_oidc_admin_password' | bosh interpolate --path /value -)

    set -x

    export CF_INT_API="https://api.${BOSH_LITE_DOMAIN}"
    export CF_DIAL_TIMEOUT=15

    export GOPATH=$PWD/go
    export PATH=$GOPATH/bin:$PATH

    pushd cf-cli-binaries
      tar xvzf cf-cli-binaries.tgz
      chmod +x cf-cli_linux_x86-64
      mkdir -p $GOPATH/bin
      mv cf-cli_linux_x86-64 $GOPATH/bin/cf
    popd

    cd $GOPATH/src/code.cloudfoundry.org/cli

    go get -u github.com/onsi/ginkgo/ginkgo

    ginkgo -r -nodes=$NODES -flakeAttempts=2 -slowSpecThreshold=60 -randomizeAllSpecs integration/isolated integration/plugin integration/push
    ginkgo -r -flakeAttempts=2 -slowSpecThreshold=60 -randomizeAllSpecs integration/global
