---
resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr
- name: bosh-lite-pool
  type: docker-image
  source:
    repository: servicesapi/bosh-lite-resource
    tag: latest

resources:
- name: cli
  type: pull-request
  source:
    repo: cloudfoundry/cli
    access_token: ((github-access-token))
    base: master # Only build PRs that want to merge to master
    disable_forks: true # Until we're sure of the security, only build PRs on the main repo, so that only people with push access can trigger
    only_mergeable: true # Don't spend resources building PRs that can't be merged.
    ignore_paths: &ciPaths
    - README.md
    - .github

- name: cli-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/cli
    branch: master
    paths: *ciPaths

- name: gcp-bosh-pool
  type: pool
  source:
    uri: git@github.com:cloudfoundry/cli-pools
    private_key: ((cli-pools-github-private-key))
    branch: master
    pool: baked-potato

- name: legacy-gcp-bosh-pool
  type: pool
  source:
    uri: git@github.com:cloudfoundry/cli-pools
    private_key: ((cli-pools-github-private-key))
    branch: master
    pool: moldy-gnocchi

- name: golang
  type: docker-image
  source:
    repository: golang
    tag: 1.9

groups:
- name: cli
  jobs:
  - units
  - claim-bosh-lite
  - integration-linux
  - integration-experimental
jobs:
- name: units
  serial: true
  plan:
  - aggregate:
    - get: pull-request
      trigger: true
    - get: cli-ci # TODO: consider using PR's version of ci?
  - aggregate:
    - task: units-linux # TODO: build other operating system's units, if resources permit
      file: cli-ci/ci/cli-pr-builder/tasks/units-linux.yml

- name: claim-bosh-lite # TODO: record PR number instead of usernames
  max_in_flight: 1
  plan:
    - aggregate:
      - get: pull-request
        trigger: true
        version: every
        passed: [units]
      - get: gcp-bosh-pool
    - do:
      - task: extract-authors-and-story-id-from-commit # TODO: extract PR info instead
        file: # TODO: write task from https://github.com/jtarchie/github-pullrequest-resource#in-clone-the-repository-at-the-given-pull-request-ref
        input_mapping: {repo: cli}
      - put: gcp-bosh-lite
        params:
          story: commit-info/story
          author_name: commit-info/author-name
          author_email: commit-info/author-email
          committer_name: commit-info/committer-name
          committer_email: commit-info/committer-email
          commit_message_prefix: CLI-

- name: integration-linux # TODO: clean this up
  serial: true
  plan:
  - aggregate:
    - get: pull-request
      trigger: true
      passed: [claim-bosh-lite]
    - get: cli-ci
    - put: bosh-lock
      resource: gcp-bosh-pool # TODO: why doesn't this just do claim-bosh-lite? What's the difference?
      params:
        acquire: true
  - do:
    - put: cli-bosh-lite
      params: # TODO: change params
        story: commit-info/story
        author_name: commit-info/author-name
        author_email: commit-info/author-email
        committer_name: commit-info/committer-name
        committer_email: commit-info/committer-email
        commit_message_prefix: CLI-
    - task: integration
      file: cli-ci/ci/cli/tasks/integration-linux.yml
      # TODO: on_failure, tell GitHub to block merging?
      ensure:
      - put: unclaim-bosh-lite
        resource: cli-bosh-lite
        params:
          operation: unclaim
          name: cli-bosh-lite/name
       params: &integration_params
        CF_INT_CLIENT_ID: 'potato-face'
        CF_INT_CLIENT_SECRET: ((cf-oauth-test-client-secret))
        CF_INT_DOCKER_IMAGE: ((dockerhub-private-image))
        CF_INT_DOCKER_USERNAME: ((dockerhub-username))
        CF_INT_DOCKER_PASSWORD: ((dockerhub-password))
        CF_INT_IGNORE_API_VERSION_CHECK: false
  ensure:
    put: gcp-bosh-pool
    params:
      release: bosh-lock

- name: integration-experimental # TODO: copy from integration-linux
