---
resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr
- name: bosh-lite-pool
  type: docker-image
  source:
    repository: servicesapi/bosh-lite-resource
    tag: latest

resources:
- name: cli
  type: pull-request
  source:
    repo: cloudfoundry/cli
    access_token: ((github-access-token))
    base: master # Only build PRs that want to merge to master
    disable_forks: true # Until we're sure of the security, only build PRs on the main repo, so that only people with push access can trigger
    only_mergeable: true # Don't spend resources building PRs that can't be merged.
    ignore_paths: &ciPaths
    - README.md
    - .github

- name: cli-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/cli
    branch: master
    paths: *ciPaths

- name: gcp-bosh-pool
  type: pool
  source:
    uri: git@github.com:cloudfoundry/cli-pools
    private_key: ((cli-pools-github-private-key))
    branch: master
    pool: baked-potato

- name: legacy-gcp-bosh-pool
  type: pool
  source:
    uri: git@github.com:cloudfoundry/cli-pools
    private_key: ((cli-pools-github-private-key))
    branch: master
    pool: moldy-gnocchi

- name: golang
  type: docker-image
  source:
    repository: golang
    tag: 1.9

- name: baseimage
  type: docker-image
  source:
    repository: phusion/baseimage
    tag: latest

- name: cli-ci-base-dockerfile
  type: git
  source:
    uri: https://github.com/cloudfoundry/cli
    branch: master
    paths: [ci/cli-base/Dockerfile]

- name: cli-ci-package-dockerfile
  type: git
  source:
    uri: https://github.com/cloudfoundry/cli
    branch: master
    paths: [ci/cli-package/Dockerfile]

- name: slack-alert
  type: slack-notification
  source:
    url: ((slack-webhook-url))

groups:
- name: cli
  jobs:
  - units
  - claim-bosh-lite
  - integration-linux
  - integration-experimental
jobs:
- name: units
  serial: true
  plan:
  - aggregate:
    - get: cli
      trigger: true
    - get: cli-ci
  - aggregate:
    - task: units-linux
      file: cli-ci/ci/cli/tasks/units-linux.yml
      on_failure: # TODO: no slack alerts on PR failures
         put: slack-alert
         params:
           channel: '#cli-eng'
           text: |
             Linux unit tests failed :(
             $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
    - task: units-osx
      file: cli-ci/ci/cli/tasks/units-osx.yml
      on_failure: # TODO: no slack alerts on PR failures
         put: slack-alert
         params:
           channel: '#cli-eng'
           text: |
             OS X unit tests failed :(
             $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
    - task: units-windows
      file: cli-ci/ci/cli/tasks/units-windows.yml
      on_failure: # TODO: no slack alerts on PR failures
         put: slack-alert
         params:
           channel: '#cli-eng'
           text: |
             Windows unit tests failed :(
             $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

- name: claim-bosh-lite # TODO: record PR number instead of usernames
  max_in_flight: 1
  plan:
    - aggregate: # TODO: make sure this only triggers if units passed for this commit
      - get: cli
        trigger: true
        version: every
      - get: services-api-meta
    - do:
      - task: extract-authors-and-story-id-from-commit
        file: services-api-meta/tasks/extract-authors-and-story-id-from-commit.yml
        input_mapping: {repo: cli}
      - put: sapi-bosh-lite
        params:
          story: commit-info/story
          author_name: commit-info/author-name
          author_email: commit-info/author-email
          committer_name: commit-info/committer-name
          committer_email: commit-info/committer-email
          commit_message_prefix: CLI-
      on_failure:
        put: sapi-internal-slack-alert
        params:
          text: *common-slack-text

- name: integration-linux # TODO: clean this up
  serial: true
  plan:
  - aggregate:
    - get: cli
      passed: [build-binaries]
    - get: cf-cli-binaries
      passed: [build-binaries]
      trigger: true
    - get: cli-ci
    - put: bosh-lock
      resource: gcp-bosh-pool
      params:
        acquire: true
  - do:
    - put: cli-bosh-lite
      params:
        story: commit-info/story
        author_name: commit-info/author-name
        author_email: commit-info/author-email
        committer_name: commit-info/committer-name
        committer_email: commit-info/committer-email
        commit_message_prefix: CLI-
    - task: integration
      file: cli-ci/ci/cli/tasks/integration-linux.yml
      # TODO: on_failure, tell GitHub not to block merging?
      ensure:
      - put: unclaim-bosh-lite
        resource: cli-bosh-lite
        params:
          operation: unclaim
          name: cli-bosh-lite/name
       params: &integration_params
        CF_INT_CLIENT_ID: 'potato-face'
        CF_INT_CLIENT_SECRET: ((client-secret))
        CF_INT_DOCKER_IMAGE: ((dockerhub-private-image))
        CF_INT_DOCKER_USERNAME: ((dockerhub-username))
        CF_INT_DOCKER_PASSWORD: ((dockerhub-password))
        CF_INT_IGNORE_API_VERSION_CHECK: false
  ensure:
    put: gcp-bosh-pool
    params:
      release: bosh-lock

- name: integration-experimental # TODO: copy from integration-linux
